trigger:
  - none  # Здесь можно указать branch для автоматического запуска, или оставить пустым для ручного запуска

pr:
  - none

# Ручной запуск pipeline
variables:
  NODE_VERSION: '16'

stages:
  - stage: Playwright_Tests
    displayName: "Run Playwright Tests"
    jobs:
      - job: PlaywrightTests
        displayName: "Execute Playwright Tests"
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          # 1. Checkout Code
          - task: Checkout@1
            displayName: "Checkout Code"

          # 2. Setup Node.js
          - task: UseNode@1
            displayName: "Setup Node.js"
            inputs:
              version: $(NODE_VERSION)

          # 3. Install Dependencies
          - script: npm install
            displayName: "Install Dependencies"

          # 4. Run Playwright Tests
          - script: npx playwright test --reporter=html
            displayName: "Run Playwright Tests"
            env:
              HEADLESS: true

          # 5. Publish HTML Report as Artifact
          - task: PublishPipelineArtifact@1
            displayName: "Publish Playwright Report"
            inputs:
              targetPath: 'playwright-report'
              artifact: 'PlaywrightReport'
              publishLocation: 'pipeline'
