trigger:
  - main  # Триггер для запуска pipeline (например, ветка main)

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '16'  # Указать используемую версию Node.js

steps:
  # 1. Checkout репозиторий
  - checkout: self
    displayName: "Checkout Repository"

  # 2. Установка Node.js
  - task: UseNode@1
    displayName: "Setup Node.js"
    inputs:
      version: $(NODE_VERSION)

  # 3. Установка зависимостей
  - script: npm install
    displayName: "Install Dependencies"

  # 4. Запуск Playwright тестов
  - script: npx playwright test --reporter=html
    displayName: "Run Playwright Tests"

  # 5. Публикация отчета как артефакта
  - task: PublishPipelineArtifact@1
    displayName: "Publish Playwright Report"
    inputs:
      targetPath: 'playwright-report'  # Папка с HTML-отчетом
      artifact: 'PlaywrightReport'    # Имя артефакта
      publishLocation: 'pipeline'

  # 6. (Опционально) Ссылка на отчет в результатах
  - script: |
      echo "##vso[task.addattachment type=Distributedtask.Core.Summary;name=Playwright Report;]$(Build.ArtifactStagingDirectory)/playwright-report/index.html"
    displayName: "Attach HTML Report"
