name: Playwright Tests

on:
  #  push:
  #    branches:
  #      - main
  #  pull_request:
  #    branches:
  #      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Run Playwright Tests
      - name: Run Playwright Tests
        env:
          HEADLESS: true
        run: npx playwright test --reporter=html

      # 5. Deploy HTML Report to GitHub Pages
      - name: Deploy Playwright Report to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
